# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/DebianThings/codehere/my_http

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/DebianThings/codehere/my_http

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/DebianThings/codehere/my_http/CMakeFiles /mnt/d/DebianThings/codehere/my_http/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/DebianThings/codehere/my_http/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named my_http

# Build rule for target.
my_http: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 my_http
.PHONY : my_http

# fast build rule for target.
my_http/fast:
	$(MAKE) -f CMakeFiles/my_http.dir/build.make CMakeFiles/my_http.dir/build
.PHONY : my_http/fast

src/deal_url_request.o: src/deal_url_request.c.o

.PHONY : src/deal_url_request.o

# target to build an object file
src/deal_url_request.c.o:
	$(MAKE) -f CMakeFiles/my_http.dir/build.make CMakeFiles/my_http.dir/src/deal_url_request.c.o
.PHONY : src/deal_url_request.c.o

src/deal_url_request.i: src/deal_url_request.c.i

.PHONY : src/deal_url_request.i

# target to preprocess a source file
src/deal_url_request.c.i:
	$(MAKE) -f CMakeFiles/my_http.dir/build.make CMakeFiles/my_http.dir/src/deal_url_request.c.i
.PHONY : src/deal_url_request.c.i

src/deal_url_request.s: src/deal_url_request.c.s

.PHONY : src/deal_url_request.s

# target to generate assembly for a file
src/deal_url_request.c.s:
	$(MAKE) -f CMakeFiles/my_http.dir/build.make CMakeFiles/my_http.dir/src/deal_url_request.c.s
.PHONY : src/deal_url_request.c.s

src/request.o: src/request.c.o

.PHONY : src/request.o

# target to build an object file
src/request.c.o:
	$(MAKE) -f CMakeFiles/my_http.dir/build.make CMakeFiles/my_http.dir/src/request.c.o
.PHONY : src/request.c.o

src/request.i: src/request.c.i

.PHONY : src/request.i

# target to preprocess a source file
src/request.c.i:
	$(MAKE) -f CMakeFiles/my_http.dir/build.make CMakeFiles/my_http.dir/src/request.c.i
.PHONY : src/request.c.i

src/request.s: src/request.c.s

.PHONY : src/request.s

# target to generate assembly for a file
src/request.c.s:
	$(MAKE) -f CMakeFiles/my_http.dir/build.make CMakeFiles/my_http.dir/src/request.c.s
.PHONY : src/request.c.s

src/response.o: src/response.c.o

.PHONY : src/response.o

# target to build an object file
src/response.c.o:
	$(MAKE) -f CMakeFiles/my_http.dir/build.make CMakeFiles/my_http.dir/src/response.c.o
.PHONY : src/response.c.o

src/response.i: src/response.c.i

.PHONY : src/response.i

# target to preprocess a source file
src/response.c.i:
	$(MAKE) -f CMakeFiles/my_http.dir/build.make CMakeFiles/my_http.dir/src/response.c.i
.PHONY : src/response.c.i

src/response.s: src/response.c.s

.PHONY : src/response.s

# target to generate assembly for a file
src/response.c.s:
	$(MAKE) -f CMakeFiles/my_http.dir/build.make CMakeFiles/my_http.dir/src/response.c.s
.PHONY : src/response.c.s

src/response_util.o: src/response_util.c.o

.PHONY : src/response_util.o

# target to build an object file
src/response_util.c.o:
	$(MAKE) -f CMakeFiles/my_http.dir/build.make CMakeFiles/my_http.dir/src/response_util.c.o
.PHONY : src/response_util.c.o

src/response_util.i: src/response_util.c.i

.PHONY : src/response_util.i

# target to preprocess a source file
src/response_util.c.i:
	$(MAKE) -f CMakeFiles/my_http.dir/build.make CMakeFiles/my_http.dir/src/response_util.c.i
.PHONY : src/response_util.c.i

src/response_util.s: src/response_util.c.s

.PHONY : src/response_util.s

# target to generate assembly for a file
src/response_util.c.s:
	$(MAKE) -f CMakeFiles/my_http.dir/build.make CMakeFiles/my_http.dir/src/response_util.c.s
.PHONY : src/response_util.c.s

src/server.o: src/server.c.o

.PHONY : src/server.o

# target to build an object file
src/server.c.o:
	$(MAKE) -f CMakeFiles/my_http.dir/build.make CMakeFiles/my_http.dir/src/server.c.o
.PHONY : src/server.c.o

src/server.i: src/server.c.i

.PHONY : src/server.i

# target to preprocess a source file
src/server.c.i:
	$(MAKE) -f CMakeFiles/my_http.dir/build.make CMakeFiles/my_http.dir/src/server.c.i
.PHONY : src/server.c.i

src/server.s: src/server.c.s

.PHONY : src/server.s

# target to generate assembly for a file
src/server.c.s:
	$(MAKE) -f CMakeFiles/my_http.dir/build.make CMakeFiles/my_http.dir/src/server.c.s
.PHONY : src/server.c.s

src/ssl_socket.o: src/ssl_socket.c.o

.PHONY : src/ssl_socket.o

# target to build an object file
src/ssl_socket.c.o:
	$(MAKE) -f CMakeFiles/my_http.dir/build.make CMakeFiles/my_http.dir/src/ssl_socket.c.o
.PHONY : src/ssl_socket.c.o

src/ssl_socket.i: src/ssl_socket.c.i

.PHONY : src/ssl_socket.i

# target to preprocess a source file
src/ssl_socket.c.i:
	$(MAKE) -f CMakeFiles/my_http.dir/build.make CMakeFiles/my_http.dir/src/ssl_socket.c.i
.PHONY : src/ssl_socket.c.i

src/ssl_socket.s: src/ssl_socket.c.s

.PHONY : src/ssl_socket.s

# target to generate assembly for a file
src/ssl_socket.c.s:
	$(MAKE) -f CMakeFiles/my_http.dir/build.make CMakeFiles/my_http.dir/src/ssl_socket.c.s
.PHONY : src/ssl_socket.c.s

src/thread_process_http.o: src/thread_process_http.c.o

.PHONY : src/thread_process_http.o

# target to build an object file
src/thread_process_http.c.o:
	$(MAKE) -f CMakeFiles/my_http.dir/build.make CMakeFiles/my_http.dir/src/thread_process_http.c.o
.PHONY : src/thread_process_http.c.o

src/thread_process_http.i: src/thread_process_http.c.i

.PHONY : src/thread_process_http.i

# target to preprocess a source file
src/thread_process_http.c.i:
	$(MAKE) -f CMakeFiles/my_http.dir/build.make CMakeFiles/my_http.dir/src/thread_process_http.c.i
.PHONY : src/thread_process_http.c.i

src/thread_process_http.s: src/thread_process_http.c.s

.PHONY : src/thread_process_http.s

# target to generate assembly for a file
src/thread_process_http.c.s:
	$(MAKE) -f CMakeFiles/my_http.dir/build.make CMakeFiles/my_http.dir/src/thread_process_http.c.s
.PHONY : src/thread_process_http.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... my_http"
	@echo "... edit_cache"
	@echo "... src/deal_url_request.o"
	@echo "... src/deal_url_request.i"
	@echo "... src/deal_url_request.s"
	@echo "... src/request.o"
	@echo "... src/request.i"
	@echo "... src/request.s"
	@echo "... src/response.o"
	@echo "... src/response.i"
	@echo "... src/response.s"
	@echo "... src/response_util.o"
	@echo "... src/response_util.i"
	@echo "... src/response_util.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... src/ssl_socket.o"
	@echo "... src/ssl_socket.i"
	@echo "... src/ssl_socket.s"
	@echo "... src/thread_process_http.o"
	@echo "... src/thread_process_http.i"
	@echo "... src/thread_process_http.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

